# Generated by Django 5.2.16 on 2026-07-12 17:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0002_alter_workspace_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCustomer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("LEMONSQUEEZY", "LemonSqueezy"),
                            ("PAYMOB", "Paymob"),
                            ("PAYPAL", "PayPal"),
                            ("PADDLE", "Paddle"),
                        ],
                        default="STRIPE",
                        max_length=20,
                        verbose_name="provider",
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="customer ID",
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_customer",
                        to="teams.workspace",
                        verbose_name="workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment customer",
                "verbose_name_plural": "payment customers",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("LEMONSQUEEZY", "LemonSqueezy"),
                            ("PAYMOB", "Paymob"),
                            ("PAYPAL", "PayPal"),
                            ("PADDLE", "Paddle"),
                        ],
                        max_length=20,
                        verbose_name="provider",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(max_length=255, unique=True, verbose_name="transaction ID"),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="amount"),
                ),
                (
                    "currency",
                    models.CharField(default="USD", max_length=10, verbose_name="currency"),
                ),
                ("status", models.CharField(max_length=50, verbose_name="status")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="teams.workspace",
                        verbose_name="workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment transaction",
                "verbose_name_plural": "payment transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("LEMONSQUEEZY", "LemonSqueezy"),
                            ("PAYMOB", "Paymob"),
                            ("PAYPAL", "PayPal"),
                            ("PADDLE", "Paddle"),
                        ],
                        default="STRIPE",
                        max_length=20,
                        verbose_name="provider",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="subscription ID",
                    ),
                ),
                (
                    "plan_id",
                    models.CharField(default="free", max_length=255, verbose_name="plan ID"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trialling", "Trialling"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                            ("inactive", "Inactive"),
                        ],
                        default="inactive",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="current period end"),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(default=False, verbose_name="cancel at period end"),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="teams.workspace",
                        verbose_name="workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
    ]
