# Generated by Django 5.2.16 on 2026-07-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_paymentcustomer_deleted_at_subscription_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        help_text="معرف الخطة الفريد (مثل: free, pro, enterprise)",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="plan name")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="monthly price"
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="yearly price"
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Stripe price ID"
                    ),
                ),
                (
                    "paymob_plan_id",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Paymob plan ID"
                    ),
                ),
                (
                    "max_members",
                    models.IntegerField(default=3, verbose_name="maximum workspace members"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="highlight as popular"),
                ),
                ("sorting_order", models.IntegerField(default=0, verbose_name="sorting order")),
            ],
            options={
                "verbose_name": "plan",
                "verbose_name_plural": "plans",
                "ordering": ["sorting_order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("feature_text", models.CharField(max_length=255, verbose_name="feature text")),
                (
                    "is_highlighted",
                    models.BooleanField(default=False, verbose_name="is highlighted"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="payments.plan",
                        verbose_name="plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan feature",
                "verbose_name_plural": "plan features",
            },
        ),
    ]
