# Generated by Django 5.1 on 2026-07-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_plan_planfeature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="id",
            field=models.CharField(
                help_text="Unique plan ID (e.g. free, pro, enterprise)",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
