# Generated by Django 5.2.16 on 2026-07-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(default="UTC", max_length=100),
        ),
    ]
